# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918302136d9b5b0239169dc5c919c2515b90acbdf793744329b1da23623a82c8bf54ac22da8b933439f87f7b8057827b56028782cc4e190deaf4729da0641e9e

test:
  secret_key_base: 2e74f25cd069e30e141493a5d80ca3acf0c96d418b863df9faecf765a4be2f6e33ffbdf8f3520fe32d56ab4d7d31295d387a6cc72d4c7abd55606a1cb0fcb237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
